development:
  secret_key_base: super_long_secret_key_for_development
  google_client_id: 87071099391-ut31r21f2j0l634c9vavu488sac3d7qr.apps.googleusercontent.com
  google_client_secret: PvBdMEYcuP66evXbaPO_1SEO